pub mod bench;
pub mod config;
#[cfg(feature = "serve")]
pub mod daemon;
pub mod export;
pub mod init;
pub mod integrate;
pub mod list;
#[cfg(feature = "mcp")]
pub mod mcp;
pub mod memory;
pub mod memory_tool;
#[cfg(feature = "embeddings")]
pub mod models;
pub mod remove;
pub mod scan;
pub mod search;
#[cfg(feature = "serve")]
pub mod serve;
pub mod status;
#[cfg(feature = "serve")]
pub mod watch;
